#!/bin/sh
# $Id$
# elvis: adsbhex         -- Find aircraft by ICAO hex code on ADSBexchange (adsbexchange.com)
# version 0.1 by Philip Collier webmaster@ab9il.net
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Find aircraft by ICAO hex code on ADSBexchange (adsbexchange.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://globe.adsbexchange.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://globe.adsbexchange.com/?icao=${escaped_args}&zoom=8"
fi
