#!/bin/sh
# $Id$
# elvis: aerobase        -- Search aircraft registrations on AeroBase (aerobasegroup.com)
# version 0.1 by Philip Collier webmaster@ab9il.net
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search aircraft regisrations at AeroBase (aerobasegroup.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments
if test -z "$w3_args"; then
    w3_browse_url "https://aerobasegroup.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://aerobasegroup.com/tail-number-lookup/${escaped_args}"
fi
